### ISSUE TITLE
Capacity to disable features

### ISSUE THREAD

**Issue by butterdroid** [cwarwicker/discord-Writer-Bot#30]
Writer-Bot is great! I'm looking forward to using it during NaNo this year.
We have a couple of other bots in the server, though, and I'd love to be able to disable some of the features (mostly the "fun" commands), because they overlap with existing functionality.

Cheers,
Carlos

**Comment by Starlight220** [comment]
Another use-case for this is partnered servers disabling commands that break/cut close with Discord ToS.
