### ISSUE TITLE
Sprint Tie doesn't give same xp.

### ISSUE THREAD

**Issue by marvelman3284** [cwarwicker/discord-Writer-Bot#47]
If first place and second place have the same wpm in a sprint they do not get the same amount of xp. As seen here: [#suggestions in the support server](https://canary.discord.com/channels/503593039541960704/727249368473796639/771110828970737694)

**Comment by kilobyte-terabyte** [comment]
@cwarwicker this can be closed (forgot to tie the PR to it)
