### ISSUE TITLE
Update goal

### ISSUE THREAD

**Issue by RavynWhyt** [cwarwicker/discord-Writer-Bot#49]
There should be a way to manually update goals for when you write without sprinting. Unless there is a way, but we haven't found it yet.

**Comment by marvelman3284** [comment]
@RavynWhyt Using `wrote` will update your goal.

**Comment by RavynWhyt** [comment]
Okies, it doesn't show up on the daily goal amout, so we weren't sure! Thanks muchly!

**Comment by cwarwicker** [comment]
It should show up on your goals every time you submit some written words. If the goal has been set.
