### ISSUE TITLE
reaasure command not working

### ISSUE THREAD

**Issue by DarkJediQueen** [cwarwicker/discord-Writer-Bot#52]
![image](https://user-images.githubusercontent.com/74501228/99189167-fad1d800-272d-11eb-845d-76fc94c7c4ed.png)
![image](https://user-images.githubusercontent.com/74501228/99189173-06250380-272e-11eb-80d3-adbe3457775e.png)
As you can see I've tried many adn the [Wiki](https://github.com/cwarwicker/discord-Writer-Bot/wiki/Fun-Commands#reassure) just states: reassure CMR - This will post a reassuring message for the user with the name "CMR". as an example. I am not exactly sure what I am doing wrong.

**Comment by cwarwicker** [comment]
Hi,

Yeah the reassure command a couple of other things aren't working at the moment. It's pinned at the top of the Bugs channel on the support server. Waiting for discord to email me back.

**Comment by DarkJediQueen** [comment]
Sorry, I have no clue about the support server so I didn't see that.

**Comment by JCMiguel** [comment]
Hi everyone,

It's great to know this issue solution is in progress. The last week I found similar behaviour in !xp top command. I just would like to add that the reassure command still works fine if the line execution contains the bot name. For example:

     cmd:     !reassure Writer-Bot
     ans:     @Writer-Bot, You will survive this. And when it’s over, I will be here and so will you.

So, in the meantime of the issue solution, with this sintax the nanowriters can take a reassure message and keep going well :)
