### ISSUE TITLE
Usability suggestion: add a confidence check for accidentally huge WPM

### ISSUE THREAD

**Issue by jrothwell** [cwarwicker/discord-Writer-Bot#57]
## Problem
We have noticed a common gotcha on our Discord server where people accidentally set (impossible) new PBs when they make typos, or forget to submit their starting word count when they join the sprint.

I think this could be resolved with a confidence check on submission, to reject word counts that would take the person's WPM above a certain threshold _(to be determined)_.

### Example 1: person doesn't check into sprint with starting word counts

Someone sets up a sprint using e.g. `!sprint for 15 in 5`, or joins a sprint with `!sprint join`. They already have a project on the go, but forgot to submit their opening word count.

Come the end of the sprint, they submit their word count, get an impossible WPM figure, and set a new PB. This can only be fixed by resetting their PB.

### Example 2: fat fingers

Someone checks into a sprint correctly, but their finger slips when they submit their closing word count. e.g. instead of entering 333 they enter 3333. Their WPM increases by an order of magnitude and their previous (legitimate) PB is wiped in favour of a new one.

## Proposed solution

Add a confidence check to `sprint.py` to either:

* stop submission of word counts with an excessive WPM
* warn people who submit excessively high word counts, to give them a chance to correct it

There are advantages and disadvantages to various 'thresholds':

* Low thresholds could stop legitimately fast typists or dictation users from submitting legitimate word counts
* Some people doing comics, pictures, etc. alias 'words' to what they're working on (e.g. 1 panel = 100 words; 1 musical track = 500 words). This could scupper their statistics
* High thresholds run the risk of not working for smaller but more 'inocuous' errors, e.g. if someone means to enter 33 but instead entered 333. However, this proposal couldn't really deal with errors like this anyway. Its principal reason to exist is to stop someone accidentally overwriting their legit PB and having to reset it because they forgot to check into a sprint or made a typo.

### Potential code solution
If the check were to exist in `run_status`, it might look something like this:

```python
        # If the speed at which the person wrote is clearly humanly impossible (>150wpm) that's an error.
        # This is to protect against cases where someone has forgotten to check in with their starting word count (e.g. `!sprint join` when they should've run `!sprint join 5253`) and gets a PB that's impossible.
        if wpm > 150:
            return await context.send(user.get_mention() + ', ' + lib.get_string('sprint:err:veryhighwpm', user.get_guild())).format(current, wpm)
            # "sprint:err:veryhighwpm" = "Your new word count {} is equivalent to {} wpm, which is physically impossible! Did you join the sprint with your starting word count? If not, join the sprint again with your word count at the START of the sprint, then re-submit your ending word count."
```

However, depending on the behaviour we want, it may be better to live elsewhere. It may also be worth refactoring where WPM and so forth are calculated.

**Comment by marvelman3284** [comment]
This sounds like a great suggestion and we have had people in the support server ask for things like this. A way to avoid the disadvantages is just to ask for the user's confirmation. If they say no, then they can revise their word count, if for example, they are a fast typer then they can confirm and submit their original word count. If you are interested in working on this feature you can fork this repo, clone the dev-env repo, and open a pull request. If you need any help you can contact me on discord - Marvelman3284#6554

**Comment by cwarwicker** [comment]
Yeah people have been asking about this recently. There's a few options I can think of:

1. Basically as above, but I would have it ask them for confirmation rather than just stop them, as they may have a reason for setting a high WPM.
2. Start storing personal best changes in the database, then let the user 'rollback' to their previous PB if they mess it up
3. Allow users to just manually set their PB, e.g. `sprint pb 34.5` or something

Not sure which of these is best.
