### ISSUE TITLE
Update specific goal amounts

### ISSUE THREAD

**Issue by cwarwicker** [cwarwicker/discord-Writer-Bot#60]
Example: 
- User starts using bot on Nov 17th
- Prior to using bot, user had already written 50000 words this year, 4000 this month.
- They set their goals for the year, month, week, day, etc...
- They want their yearly and monthly goals to take into account the words they've already written before using the bot, but if they do a `wrote 50000` for example, it will massively over achieve their weekly and daily goals.

So what they essentially want is a command to just update the value of a specific goal, without affecting anything else.

Format: `goal update <type> <amount>`, e.g: `goal update yearly 50000` `goal update monthly 4000`, etc...

So this should just update the value in the database for their goal, not changing anything else.

**Comment by marvelman3284** [comment]
Working on this
