### ISSUE TITLE
Leaderboard display bug

### ISSUE THREAD

**Issue by outlaw45** [cwarwicker/discord-Writer-Bot#63]
I run a writing server with writer-bot we have been hosting events for specific months and our users have been happy to use the leaderboard but for about a month we cannot use the !event top command, it only shows the outline of the message without using user data so there is no leaderboard for us to see.
We love to use writer-bot and would be happy to see this future fixed! 
![leaderboard bug](https://user-images.githubusercontent.com/74819061/99876265-b1d6c380-2c06-11eb-9124-77babda30fb3.JPG)

**Comment by cwarwicker** [comment]
Should be fixed now, hopefully.
