### ISSUE TITLE
Writer Bot has been down since last night

### ISSUE THREAD

**Issue by lokon100** [cwarwicker/discord-Writer-Bot#71]
Hello! I went to sprint last night and saw that Writer Bot was down, and it's currently down.

**Comment by DarkJediQueen** [comment]
Not the coder but the issue is known. Discord did some updates and the bot needs to be restarted, I think, and then it will be good. Owner has said they will update as soon as they get to a computer in a few hours.

**Comment by lokon100** [comment]
Thanks!!
