### ISSUE TITLE
enhancement: update project

### ISSUE THREAD

**Issue by contemplativepancakes** [cwarwicker/discord-Writer-Bot#72]
when you update the word count of a project, I think it should count towards your total word count as well. My goal is to do no math, I would love it if I didn't have to add and subtract words to get my counts.

**Comment by DarkJediQueen** [comment]
The wrote command is what you use when you want to do that !wrote 333 (Project) adds to both your total word count as well as your project. 

Not everyone starts with a new project. Sometimes people add in projects they have written on before so adding in the words when creating the project then means they will need to subtract those words from their total word counts.

**Comment by Starlight220** [comment]
I think that @DarkJediQueen's response closes this, and it seems that @contemplativepancakes isn't active.

I think that this issue can be closed; @cwarwicker?
