### ISSUE TITLE
!project complete does not work

### ISSUE THREAD

**Issue by nothalfbad** [cwarwicker/discord-Writer-Bot#73]
When using !project complete command Writer Bot returns: Invalid project command. Noticed this issue a month ago on my server. Any idea what to do?

**Comment by nothalfbad** [comment]
_!project help_ returns Invalid command as well.

**Comment by DarkJediQueen** [comment]
The term you are looking for is finished, not complete and the command is !help project. You can also look at the wiki here on github for a indepth look at the commands.

**Comment by cwarwicker** [comment]
I changed projects a while ago, so now they can have various different statuses. You can change it with `!project status <shortname> finished`

More info here: https://github.com/cwarwicker/discord-Writer-Bot/wiki/Writing-Commands#project

**Comment by nothalfbad** [comment]
Thank you!
