### ISSUE TITLE
Remind has broke

### ISSUE THREAD

**Issue by purpleglade** [cwarwicker/discord-Writer-Bot#74]
Starting earlier this week, my server using the writer bot stopped giving reminders to people. You can look at your list of reminders and each of them will say, 'Any time now!' to when they will go off next. We tried adding new reminders, deleting old ones and messing with the settings. Nothing worked. 

I recently discovered that this is an issue plaguing other discord servers as well, leading me to think it is the bot. Either discord changed something and broke it, or the bot  just needs to be restarted. Either way, I figured you might want to know.

**Comment by cwarwicker** [comment]
I think this is fixed now.
