### ISSUE TITLE
Not Responding to Commands in Thread

### ISSUE THREAD

**Issue by Ravenabi** [cwarwicker/discord-Writer-Bot#78]
Bot does not respond to created threads in discord.

**Comment by Starlight220** [comment]
This is known, the bot hasn't been updated for threads.

**Comment by DeltaTango-11** [comment]
> This is known, the bot hasn't been updated for threads.

Do we know if they plan on updating it to allow it to post/respond in threads? It's been quite awhile now and is a feature I really need.

**Comment by Starlight220** [comment]
Can you give a use case where this would be useful?

Regardless, the current large change in the works is [Slash Commands](https://github.com/cwarwicker/discord-Writer-Bot/wiki/Slash-Commands). I don't see Threads being added before that's completed (which will take a while).

**Comment by Starlight220** [comment]
Slash commands work in threads; I think this can be closed.
