### ISSUE TITLE
"sprint join same" only uses wordcount from reporting phase

### ISSUE THREAD

**Issue by kilobyte-terabyte** [cwarwicker/discord-Writer-Bot#97]
## Description
When sprinting, sometimes users will report their word count before the sprint has finished. That word count then gets carried over into the final tally (for instance, if someone steps away 5 minutes before the sprint ends and reports 500 words, their sprint total = 500 words). However, when that same user does `sprint join same`, they get added to the sprint with 0 words.

The "same" argument works fine if the wordcount is reported after Writer-Bot asks.

## Steps to replicate
1. Join a sprint (with any wordcount)
2. Report wordcount before sprint ends (for instance, 500).
3. Sprint ends -> reports w/ correct wordcount
4. Start a new sprint
5. Join w/ `sprint join same`.
6. Observe that starting wordcount = 0. Expected: 500 (or = the earlier input).

**Comment by cwarwicker** [comment]
Should be fixed now.
